const API='https://alshaqi.alwaysdata.net/api.php';
const tokenKey='bissan_admin_token';
const token=sessionStorage.getItem(tokenKey);
const status=document.getElementById('status');
async function api(action,body){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+(sessionStorage.getItem(tokenKey)||'')},body:JSON.stringify({action,...(body||{})})});const ct=r.headers.get('content-type')||'';if(!ct.includes('application/json'))throw new Error('server');const data=await r.json();if(!r.ok||data.ok===false)throw new Error(data.message||'error');return data}
const loginForm=document.getElementById('loginForm');
if(loginForm){loginForm.addEventListener('submit',async e=>{e.preventDefault();status.className='status';status.textContent='جارٍ التحقق…';try{const r=await api('login',{password:document.getElementById('password').value});sessionStorage.setItem(tokenKey,r.token);location.href='index.html'}catch(err){status.className='status err';status.textContent='كلمة المرور غير صحيحة أو تعذر الاتصال بالخادم'}})}
const list=document.getElementById('filesList');
if(list){if(!token){location.href='login.html'}else load();}
async function load(){try{const r=await api('list');const files=r.files||[];document.getElementById('count').textContent=files.length+' ملف';if(!files.length){list.innerHTML='<div class="empty">لا توجد ملفات حالياً</div>';return}list.innerHTML='';files.forEach(f=>{const el=document.createElement('div');el.className='item';el.innerHTML='<div class="icon">▣</div><div class="info"><div class="name"></div><div class="meta"></div></div><button class="download">تنزيل</button>';el.querySelector('.name').textContent=f.original_name;el.querySelector('.meta').textContent=f.size+' · '+f.date;el.querySelector('.download').onclick=()=>download(f.id,f.original_name,el);list.appendChild(el)})}catch(e){sessionStorage.removeItem(tokenKey);location.href='login.html'}}
async function download(id,name,row){const b=row.querySelector('.download');b.disabled=true;b.textContent='…';try{const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+(sessionStorage.getItem(tokenKey)||'')},body:JSON.stringify({action:'download',id})});if(!r.ok)throw new Error();const blob=await r.blob();const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);row.remove();const c=document.getElementById('count');const n=Math.max(0,parseInt(c.textContent)||1);c.textContent=n-1+' ملف';}catch(e){b.disabled=false;b.textContent='تنزيل';status.className='status err';status.textContent='تعذر تنزيل الملف'}}
const logout=document.getElementById('logout');if(logout)logout.onclick=()=>{sessionStorage.removeItem(tokenKey);location.href='login.html'};
