const API_BASE='https://alshaqi.alwaysdata.net';
const token=localStorage.getItem('bisan_admin_token');
if(!token) location.replace('login.html');
const filesBox=document.getElementById('files'),count=document.getElementById('count'),msg=document.getElementById('message');
async function api(action,options={}){const r=await fetch(API_BASE+'/api.php?action='+encodeURIComponent(action),{...options,headers:{...(options.headers||{}),Authorization:'Bearer '+token}});if(r.status===401){localStorage.removeItem('bisan_admin_token');location.replace('login.html');throw new Error('auth')}return r}
function esc(s){const d=document.createElement('div');d.textContent=s;return d.innerHTML}
async function load(){try{const r=await api('list');const d=await r.json();if(!d.ok)throw new Error(d.message);count.textContent=d.files.length+' ملف';if(!d.files.length){filesBox.innerHTML='<div class="empty">لا توجد ملفات حالياً</div>';return}filesBox.innerHTML=d.files.map(f=>`<div class="item"><div style="font-size:25px">📄</div><div class="info"><div class="name">${esc(f.original_name)}</div><div class="meta">${esc(f.size)} · ${esc(f.date)}</div></div><button class="download" data-id="${esc(f.id)}">تنزيل</button></div>`).join('');document.querySelectorAll('.download').forEach(b=>b.addEventListener('click',()=>downloadFile(b.dataset.id,b)))}catch(e){if(e.message!=='auth')msg.textContent='تعذر تحميل الملفات'}}
async function downloadFile(id,button){button.disabled=true;button.textContent='جاري التجهيز...';try{const r=await api('ticket',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});const d=await r.json();if(!d.ok)throw new Error(d.message);window.location.href=API_BASE+'/api.php?action=download&ticket='+encodeURIComponent(d.ticket)}catch(e){msg.textContent=e.message||'تعذر تنزيل الملف';button.disabled=false;button.textContent='تنزيل'}}
document.getElementById('logout').addEventListener('click',async()=>{try{await api('logout',{method:'POST'})}catch(_){}localStorage.removeItem('bisan_admin_token');location.replace('login.html')});load();
